version: "3.9"

services:
  crawler:
      build:
        context: applications/crawler
        dockerfile: Dockerfile
        target: base
      volumes:
        - ./applications/crawler/src:/home/node/app/src
      ports:
        - '1782:80'
      command: yarn dev
  api:
      build:
        context: applications/api
        dockerfile: Dockerfile
        target: base
      volumes:
        - ./applications/api/src:/home/node/app/src
      ports:
        - '1780:80'
      command: yarn dev
  client:
      build:
        context: applications/client
        dockerfile: Dockerfile
        target: base
      volumes:
        - ./applications/client/src:/home/node/app/src
      ports:
        - '1781:80'
      command: yarn dev --port 80 --host
  mongo:
      image: mongo
      volumes:
        - ./mongodb_config:/data/configdb
        - ./mongodb_data:/data/db
      ports:
        - '27018:27017'
      command: mongod --quiet --logpath /dev/null
