version: "3.9"
services:
  crawler:
      build:
        context: applications/crawler
        dockerfile: Dockerfile
        target: production
      command: node build/src/index.js
  api:
      build:
        context: applications/api
        dockerfile: Dockerfile
        target: production
      command: node build/src/index.js
      ports:
        - '1780:80'
  mongo:
      image: mongo
      volumes:
        - ./mongodb_data:/data/db
      ports:
        - '27018:27017'
      command: mongod --quiet
