version: "3.9"
services:
  crawler:
    build:
      context: applications/crawler
      dockerfile: Dockerfile
      target: production
    command: node build/index.js
  mongo:
      image: mongo
      volumes:
        - ./mongodb_data:/data/db
      ports:
        - '27017:27017'