version: "3.9"
services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/home/node/app
    container_name: ts-node-docker
    command: npm run dev
  mongo:
      image: mongo
      volumes:
        - ./mongodb_data:/data/db
      ports:
        - '27018:27017'
      command: mongod --quiet --logpath /dev/null